### ISSUE TITLE
dot successful on larger coords file (81M), but failing on smaller coords file (18M)

### ISSUE THREAD

**Issue by chunlinxiao** [dnanexus/dot#8]
for some reason, DOT failing on smaller coords file (~18M in size), but it have no problem to generate dot plot for a ~81M coords file.  do you have any idea? thanks

**Comment by chunlinxiao** [comment]
Noticed that the index file has 12.7M in size for the  coords files with 18M in size.

**Comment by MariaNattestad** [comment]
The index file has to be read into memory in the web application, so 12.7 Mb can be overwhelming to the web browser. You can reduce the size of the index file by filtering out smaller query sequences (usually contigs) from the delta file before processing it with dotPrep.py.
